### ISSUE TITLE
[top nav] Approach dropdown menu order and capitalization

### ISSUE THREAD

**Issue by mbiyimoh** [IBM-Design/design-website#130] opened 2019-01-24 11:15 UTC
Rearrange the order of the Approach dropdown menu to:

1) Overview
2) Design Philosophy
3) Design Thinking
4) Design Services

Also capitalize Philosophy, Thinking and Services

**Comment by alisonjoseph** [comment] 2019-01-24 13:17
duplicate of #115

**Closed by alisonjoseph** 2019-01-24 13:17 UTC
Labels: type: duplicate 👯
